/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBoardRouteImport } from './routes/api/board'
import { Route as ApiBriefingRouteImport } from './routes/api/briefing'
import { Route as ApiGeminiTestRouteImport } from './routes/api/gemini-test'
import { Route as ApiSupabaseTestRouteImport } from './routes/api/supabase-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefingRoute = ApiBriefingRouteImport.update({
  id: '/api/briefing',
  path: '/api/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiTestRoute = ApiGeminiTestRouteImport.update({
  id: '/api/gemini-test',
  path: '/api/gemini-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabaseTestRoute = ApiSupabaseTestRouteImport.update({
  id: '/api/supabase-test',
  path: '/api/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/gemini-test': typeof ApiGeminiTestRoute
  '/api/supabase-test': typeof ApiSupabaseTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/gemini-test': typeof ApiGeminiTestRoute
  '/api/supabase-test': typeof ApiSupabaseTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/board': typeof ApiBoardRoute
  '/api/briefing': typeof ApiBriefingRoute
  '/api/gemini-test': typeof ApiGeminiTestRoute
  '/api/supabase-test': typeof ApiSupabaseTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/board'
    | '/api/briefing'
    | '/api/gemini-test'
    | '/api/supabase-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/board'
    | '/api/briefing'
    | '/api/gemini-test'
    | '/api/supabase-test'
  id:
    | '__root__'
    | '/'
    | '/api/board'
    | '/api/briefing'
    | '/api/gemini-test'
    | '/api/supabase-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBoardRoute: typeof ApiBoardRoute
  ApiBriefingRoute: typeof ApiBriefingRoute
  ApiGeminiTestRoute: typeof ApiGeminiTestRoute
  ApiSupabaseTestRoute: typeof ApiSupabaseTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/briefing': {
      id: '/api/briefing'
      path: '/api/briefing'
      fullPath: '/api/briefing'
      preLoaderRoute: typeof ApiBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-test': {
      id: '/api/gemini-test'
      path: '/api/gemini-test'
      fullPath: '/api/gemini-test'
      preLoaderRoute: typeof ApiGeminiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase-test': {
      id: '/api/supabase-test'
      path: '/api/supabase-test'
      fullPath: '/api/supabase-test'
      preLoaderRoute: typeof ApiSupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBoardRoute: ApiBoardRoute,
  ApiBriefingRoute: ApiBriefingRoute,
  ApiGeminiTestRoute: ApiGeminiTestRoute,
  ApiSupabaseTestRoute: ApiSupabaseTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
